server:
  port: 8080
#  tomcat post缓冲区不够大·在此设置
  tomcat:
    max-http-post-size: 8192


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fullstack?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true  # 自动建表

# 描述信息.就时监控info端点消息
info:
  blog-url: http://uepyrr.coding-pages.com/
  author: zhangbo
  version: "@project.version@"

management:
  endpoint:
    shutdown:
      enabled: false  # 可以关闭制定的端点
    health:
      enabled: true  # 因为关系了默认开启的`所有单独开启
    loggers:
      enabled: true
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"         # 注意这个暴露,只能暴露开启激活的端口
#    enabled-by-default: false  # 这就关闭默认开启激活的端点